server:
  address: 0.0.0.0
  port: 9999
  servlet:
    context-path: /GerenciamentoDeUsuarios

jwt:
  secret: minha-chave-super-secreta-e-segura-minha-chave-super-secreta-e-segura
  expiration: 86400000




spring:
  application:
    name: usuarios

  data:
    mongodb:
      uri: mongodb+srv://admin:LuizJoao123@cluster.y2vw5.mongodb.net/
      database: usuarios

